sudo: false
language: generic
cache:
    directories:
        - "$HOME/.stack/"
        - "$HOME/.local/bin/"
        - ".stack-work/"

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
    - stack --no-terminal test --only-dependencies
jobs:
    include:
        - stage: Run test
          script: stack --no-terminal test --fast
        - stage: Run test pedantic
          script:
              - stack clean
              - stack --no-terminal test --fast --pedantic
        - stage: Run Hlint
          script: curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .

notifications:
    email: false
