name:                ElGamalEncryptionHs
version:             0.1.0.0
github:              "falgon/ElGamalEncryptionHs"
license:             BSD3
author:              "roki"
maintainer:          "falgon53@yahoo.co.jp"
copyright:           "Copyright (C) 2018 roki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/falgon/ElGamalEncryptionHs#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- random
- HUnit

library:
  source-dirs: src

executables:
  ElGamalEncryptionHs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ElGamalEncryptionHs

tests:
  ElGamalEncryptionHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ElGamalEncryptionHs
